apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificaciones
  template:
    metadata:
      labels:
        app: notificaciones
    spec:
      containers:
      - name: notificaciones-app
        image: ryuko67/godofgames-envios:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-notificaciones-service:5432/godofgames_notificaciones
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "Bullseye"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: SPRING_RABBITMQ_USERNAME
          value: "godofgames"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "godofgames123"
        - name: SPRING_MAIL_USERNAME
          value: "diegolaraa10@gmail.com"
        - name: SPRING_MAIL_PASSWORD
          value: "pxbnybfdiikqvzqs"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 90
          periodSeconds: 15
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notificaciones-service
spec:
  selector:
    app: notificaciones
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP