spring.application.name=Notificaciones
server.port=8088

# Base de datos
spring.datasource.url=jdbc:postgresql://postgres-service:5432/godofgames_notificaciones
spring.datasource.username=postgres
spring.datasource.password=Bullseye

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# RabbitMQ
spring.rabbitmq.host=rabbitmq-service
spring.rabbitmq.port=5672
spring.rabbitmq.username=godofgames
spring.rabbitmq.password=godofgames123

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=diegolaraa10@gmail.com
spring.mail.password=pxbnybfdiikqvzqs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always